# str="Rohit,Virat,MS,Ravindra"
# print(str)
# print(id(str))
# d=str
# print(d)
# print(id(d))
# d.replace("Ravindra","Ravichandran")
# print(d.replace("Ravindra","Ravichandran"))
# print(id(d))
# m=d.replace("Ravindra","Ravichandran")
# print(m)
# print(id(m))

# print(str.split("."))
# print(str.split("It"))
# state="Maharashtra"
# dist="Pune"
# address=state.join(dist)
# print(address)
# print("MH".join("IN"))
# l=['1','2','3','4','5']
# s="*"
# print(s.join(l))
# l1=["R","O","C","K"]
# print("".join(l1))
# l2="".join(l1)
# print(id(l1))
# print(id(l2))
# s1="Thane"
# print(s1.upper())
# s2="PUNE"
# print(s2.lower())
# s3="PuNe"
# print(s3.swapcase())
# s4="pune"
# print(s4.title())
# s4="punE"
# print(s4.title())
# s5="pune,thane,mumbai"
# print(s5.capitalize())
# print(s5.title())
# print(s5.startswith("TH"))
# print(s5.startswith("pu"))
# print(s5.endswith("TH"))
# print(s5.endswith("ai"))
# print(s5.isdigit())
# s6="123"
# print(s6.isdigit())
# s7="rock"
# print(s7.isalpha())
# print(s7.isdigit())
# print(s7.isalnum())
# print(s6.isalnum())

