# str="Rohit,Virat,MS,Ravindra"
# print(str)
# print(id(str))
# d=str
# print(d)
# print(id(d))
# d.replace("Ravindra","Ravichandran")
# print(d.replace("Ravindra","Ravichandran"))
# print(id(d))
# m=d.replace("Ravindra","Ravichandran")
# print(m)
# print(id(m))